# Generated by Django 5.1.2 on 2024-10-13 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belu_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beluuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='belu_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
